### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by robmarkcole** [Luo-Z13/GLH-Bridge-page#1]
Hello
would you consider hosting the dataset on Zenodo/Huggingface? Baidu drive is not easy to access, thanks

**Comment by Luo-Z13** [comment]
> Hello would you consider hosting the dataset on Zenodo/Huggingface? Baidu drive is not easy to access, thanks

Certainly! The dataset will be uploaded in the coming days.

**Comment by Luo-Z13** [comment]
> Hello would you consider hosting the dataset on Zenodo/Huggingface? Baidu drive is not easy to access, thanks

The dataset has been uploaded to hugging face in https://huggingface.co/datasets/ll-13/GLH-Bridge
